name: Shoptet API-SDK tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [master, main]
  schedule:
    - cron: '0 8 * * 1' # At 08:00 on Monday

env:
  php-tools: 'composer:v2'

jobs:
  phpcs:
    name: Code sniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: composer phpcs

  phpstan:
    name: PHPstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: composer phpstan

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: composer lint

  test-unit:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: composer tests:unit
